---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: /:title ## disables post output
timezone: null
lsi: false
markdown: kramdown
encoding: utf-8

### content configuration ###
title:       "Osveščanje o kožnih alergenih in boleznih"
keywords:    "OOKAB, kožne bolezni, psoriaza"
description: "Spletna stran projekta OOKAB - osveščanje o kožnih alergenih in boleznih"
source_link: "https://ookab.github.io/web/"
favicon:     "assets/img/favicon.ico"
touch_icon:  "assets/img/apple-touch-icon.png"
logo:        "assets/img/logo.svg"
google_analytics_key: UA-114397295-1


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#49a7e9'
  green:     '#9bcf2f'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'

kramdown:
  auto_ids:  false

